/** Países y territorios de habla hispana + Otro (orden alfabético por etiqueta). */
export const SPANISH_SPEAKING_COUNTRIES = [
  { value: "Alemania (comunidad hispana)", label: "Alemania (comunidad hispana)" },
  { value: "Andorra", label: "Andorra" },
  { value: "Argentina", label: "Argentina" },
  { value: "Belice", label: "Belice" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Chile", label: "Chile" },
  { value: "Colombia", label: "Colombia" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cuba", label: "Cuba" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "España", label: "España" },
  { value: "Estados Unidos", label: "Estados Unidos" },
  { value: "Filipinas", label: "Filipinas" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guinea Ecuatorial", label: "Guinea Ecuatorial" },
  { value: "Honduras", label: "Honduras" },
  { value: "México", label: "México" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Panamá", label: "Panamá" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Perú", label: "Perú" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "República Dominicana", label: "República Dominicana" },
  { value: "Uruguay", label: "Uruguay" },
  { value: "Venezuela", label: "Venezuela" },
  { value: "Otro", label: "Otro" },
] as const;
